### ISSUE TITLE
How to map Freebase id to Wikipedia name?

### ISSUE THREAD

**Issue by mubidiy** [quqxui/MPIKGC#2]
Hello author, may I ask how to map freebase id to wikipedia name? For example the data in the file "FB15k_mid2name.txt", Thanks.

**Comment by quqxui** [comment]
Thank you for your interest in our work. The fb15k237 dataset and the corresponding FB15k_mid2name.txt file can be found at https://github.com/chenchens190009/CSProm-KG. However, I am not entirely sure about the rule for mapping Freebase IDs to Wikipedia names.

Maybe you can explore KG alignment repositories, you can check out https://github.com/mniepert/mmkb?tab=readme-ov-file. This repo provides "sameAs" links between FB15k, DBpedia15k, and YAGO15k.

Another repo you might find useful is https://github.com/nju-websoft/OpenEA. It offers links between DBpedia (2016-10), Wikidata (20160801), and YAGO3.

**Comment by mubidiy** [comment]
Thanks very much for your detailed answer, which has been of great help to me. Best wishes to you! @quqxui
