### ISSUE TITLE
merge.py  ：  The function on the last line lacks a parameter

### ISSUE THREAD

**Issue by gyf6666** [quqxui/MPIKGC#3]
Traceback (most recent call last):
  File "merge.py", line 228, in <module>
    merge_srcdes_srckeywords_rel2sentence_struc_srckeywords_top3_selfloop('struc_srckeywords_top3_selfloop')
TypeError: merge_srcdes_srckeywords_rel2sentence_struc_srckeywords_top3_selfloop() missing 1 required positional argument: 'top_loop'

**Comment by quqxui** [comment]
Hi, it lack an argument for specified relation enhancement method. It can be changed to this code:

```python
merge_srcdes_srckeywords_rel2sentence_struc_srckeywords_top3_selfloop(['rel2sentence'], 'struc_srckeywords_top3_selfloop')
```
